In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
project_path = "/global/cfs/cdirs/des/zhou/spt_lensing/"
import os

In [2]:
spt_rel_path = "spt_data/redmapperY3-SPTconf.fits"

In [3]:
halo_df_path = os.path.join(project_path,"data/lambda_spt_combined.pkl")
halo_df = pd.read_pickle(halo_df_path)

In [4]:
halo_df

,R_lambda_60,lambda_60,R_lambda_30_noperc,lambda_30_noperc,R_lambda_30,lambda_30,R_lambda_15,lambda_15,R_lambda_1,lambda_1,...,pos_y,pos_z,mean_ln_zeta,mean_ln_lambda,zeta,xi,xi_gt_45,xi_gt_5,zeta_gt_2,select
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,415.166016,856.251831,-8.618753,None,0.000188,4.178435,0.0,0.0,0.0,0.0
1,0.495934,3.0,0.525306,4.0,0.495934,3.0,0.495934,3.0,0.495934,3.0,...,414.536774,856.803711,-4.997203,None,0.006090,0.965050,0.0,0.0,0.0,0.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,415.929810,856.218750,-7.717088,None,0.000589,3.032619,0.0,0.0,0.0,0.0
3,0.525306,4.0,0.525306,4.0,0.525306,4.0,0.525306,4.0,0.525306,4.0,...,416.008942,856.025208,-6.653800,None,0.001281,2.686348,0.0,0.0,0.0,0.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,416.560669,855.756653,-8.724588,None,0.000172,1.018350,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9859095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,561.514404,888.496399,-9.094530,None,0.000094,1.446782,0.0,0.0,0.0,0.0
9859096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,560.016357,882.976013,-8.724588,None,0.000202,0.982131,0.0,0.0,0.0,0.0
9859099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,571.308411,854.020569,-8.961055,None,0.000121,3.074231,0.0,0.0,0.0,0.0
9859102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,564.850891,851.839539,-10.646326,None,0.000024,0.810190,0.0,0.0,0.0,0.0
9859103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,548.500488,844.104858,-9.787875,None,0.000047,3.673126,0.0,0.0,0.0,0.0

In [5]:
def selecting_lambda_matching_mass(self, lnlam_min=np.log(20), lnlam_max=np.log(30)):
    sel = (self.lnlam > lnlam_min)&(self.lnlam < lnlam_max)
    lnMwl_sel = np.mean(self.lnMwl[sel])

    lnM_sel = lnM[sel]
    nbins = 100
    lnMbins = np.linspace(min(lnM_sel)-0.1, max(lnM_sel)+0.1, nbins+1)

    lnMwl_weighted = 0
    for i in range(nbins):
        lnMmin = lnMbins[i]
        lnMmax = lnMbins[i+1]
        sel2 = (lnM_sel >= lnMmin)&(lnM_sel < lnMmax) # mass that falls in the lambda range 
        weight = len(lnM_sel[sel2])/len(lnM_sel) # fraction of selected mass that falls in the mass range bin
        if weight > 0:
            sel3 = (lnM >= lnMmin)&(lnM < lnMmax)
            lnMwl_weighted += np.mean(self.lnMwl[sel3]) * weight

    theory = self.r * self.scatter_wl * (self.lnlam - lnlam_mean)/self.scatter_lam 
    theory = np.mean(theory[sel])

    return lnMwl_sel-lnMwl_weighted, theory

In [6]:
d30_mask= (~np.isnan(halo_df[f"lambda_30"])) & (~np.isnan(halo_df['pos_x']))

In [7]:
halo_d30 = halo_df[d30_mask]

In [16]:
lambda_min, lambda_max = 20,30
lambda_mask = (halo_df['lambda_30'] > lambda_min) & (halo_df['lambda_30'] < lambda_max)
# what is the Mwl to use?

In [15]:
nbins = 100
lambda_bins = np.linspace(np.log(lambda_min+0.1), np.log(lambda_max) + 0.1, nbins + 1)